 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/asanas", type: :request do
  # Asana. As you add validations to Asana, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Asana.create! valid_attributes
      get asanas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      asana = Asana.create! valid_attributes
      get asana_url(asana)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_asana_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      asana = Asana.create! valid_attributes
      get edit_asana_url(asana)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Asana" do
        expect {
          post asanas_url, params: { asana: valid_attributes }
        }.to change(Asana, :count).by(1)
      end

      it "redirects to the created asana" do
        post asanas_url, params: { asana: valid_attributes }
        expect(response).to redirect_to(asana_url(Asana.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Asana" do
        expect {
          post asanas_url, params: { asana: invalid_attributes }
        }.to change(Asana, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post asanas_url, params: { asana: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested asana" do
        asana = Asana.create! valid_attributes
        patch asana_url(asana), params: { asana: new_attributes }
        asana.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the asana" do
        asana = Asana.create! valid_attributes
        patch asana_url(asana), params: { asana: new_attributes }
        asana.reload
        expect(response).to redirect_to(asana_url(asana))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        asana = Asana.create! valid_attributes
        patch asana_url(asana), params: { asana: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested asana" do
      asana = Asana.create! valid_attributes
      expect {
        delete asana_url(asana)
      }.to change(Asana, :count).by(-1)
    end

    it "redirects to the asanas list" do
      asana = Asana.create! valid_attributes
      delete asana_url(asana)
      expect(response).to redirect_to(asanas_url)
    end
  end
end
